/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shashank HP
 */
public class insertteacher extends javax.swing.JFrame {

    /**
     * Creates new form insertteacher
     */
    public insertteacher() {
        initComponents();
        
        bgImage();
        table_update();
    }

    
    public void bgImage() {
    
       ImageIcon icon = new ImageIcon("bg.jpg");
       
       Image img = icon.getImage();
       Image imgScale = img.getScaledInstance(bglabel.getWidth(), bglabel.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon scaledIcon = new ImageIcon(imgScale); 
       bglabel.setIcon(scaledIcon);
      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddr = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        bglabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 203, 131, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Teacher Ph. No. ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 289, 131, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 455, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 358, 104, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 358, 105, 31));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 165, 276, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tid", "tname", "tphno", "caddr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 127, 506, 378));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Teacher Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 163, 131, -1));

        txtaddr.setColumns(20);
        txtaddr.setRows(5);
        jScrollPane2.setViewportView(txtaddr);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 203, 276, 68));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register/Update teacher details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 30, 514, -1));

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 291, 276, -1));

        bglabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con1;
    PreparedStatement insert;
      
    private void table_update(){
      
       int c;
          try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/kindergarten?useSSL=false","root","Shashank-ssk");
                    
                    insert = con1.prepareStatement("select * from teacher");
                    ResultSet rs = insert.executeQuery();
                    
                    ResultSetMetaData Rss = (ResultSetMetaData) rs.getMetaData();
                    c = Rss.getColumnCount();
                    
                    DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                    Df.setRowCount(0);
                    
                    while(rs.next()) {
                    
                        Vector v = new Vector();
                    
                        for(int a = 1; a<=c; a++){
                            
                            v.add(rs.getString("tid"));
                            v.add(rs.getString("tname"));
                            v.add(rs.getString("tphno"));
                            v.add(rs.getString("taddr"));
                                
                        }
                    
                        Df.addRow(v);
  
                    } 
          }
            catch (ClassNotFoundException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (SQLException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            }
      
      }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        teacherinfo obj = new teacherinfo();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
         
         int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
                String name = txtname.getText();
                String num = txtno.getText();
                String addr = txtaddr.getText();
        
        if(name.isEmpty() || addr.isEmpty() )
                    JOptionPane.showMessageDialog(this,"Fill all the details");

                else{
         try {

                int val = 0;
                
                for (int i = 0; i < num.length(); i++) { 
                    if (Character.isDigit(num.charAt(i))) { 
                        val = 1; 
                    } 
                    else { 
                        val = 0; 
                    }   
                } 
                
          
                if (num.length()!=10 || val == 0)
                {
                     JOptionPane.showMessageDialog(this,"Invalid Number");
                }
                
                else{
                
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/kindergarten?useSSL=false","root","Shashank-ssk");

                    insert = con1.prepareStatement("update teacher set tname = ?, tphno =?, taddr = ? where tid=?");
                    insert.setString(1,name);
                    insert.setString(2,num);
                    insert.setString(3,addr);
                    insert.setInt(4,id);

                    insert.executeUpdate();

                    JOptionPane.showMessageDialog(this,"Record Updated");
                    table_update();

                    txtname.setText("");
                    txtno.setText("");
                    txtaddr.setText("");
                    txtname.requestFocus();
                }
        }
                 
        catch (ClassNotFoundException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (SQLException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
                
                String name = txtname.getText();
                String num = txtno.getText();
                String addr = txtaddr.getText();
                
                int val = 0;
                
                for (int i = 0; i < num.length(); i++) { 
                    if (Character.isDigit(num.charAt(i))) { 
                        val = 1; 
                    } 
                    else { 
                        val = 0; 
                    }   
                } 
                
          
                if (num.length()!=10 || val == 0)
                {
                     JOptionPane.showMessageDialog(this,"Invalid Number");
                }
                
                else{
                    if(name.isEmpty() || addr.isEmpty() )
                    JOptionPane.showMessageDialog(this,"Fill all the details");

                else{
                
            try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/kindergarten?useSSL=false","root","Shashank-ssk");
                    
                    insert = con1.prepareStatement("insert into teacher( tname, tphno, taddr)values(?,?,?)");
                    insert.setString(1, name);
                    insert.setString(2, num);
                    insert.setString(3, addr);
                    insert.executeUpdate();
                    
                    
                    JOptionPane.showMessageDialog(this,"Record Added");
                    table_update();

                    txtname.setText("");
                    txtaddr.setText("");
                    txtno.setText("");
                    txtname.requestFocus();
                            

            } 
            catch (ClassNotFoundException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (SQLException ex) {
                    Logger.getLogger(newchild.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }
                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();

       txtname.setText(Df.getValueAt(selectedIndex , 1).toString());
       txtno.setText(Df.getValueAt(selectedIndex , 2).toString());
       txtaddr.setText(Df.getValueAt(selectedIndex , 3).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertteacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bglabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtaddr;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtno;
    // End of variables declaration//GEN-END:variables
}
